"""add manga and manga similarity tables

Revision ID: 6585d8383184
Revises: 53c24a3095ed
Create Date: 2026-09-25 22:11:18.791838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6585d8383184'
down_revision: Union[str, Sequence[str], None] = '53c24a3095ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_english', sa.String(length=255), nullable=True),
    sa.Column('title_japanese', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('publishing', sa.Boolean(), nullable=True),
    sa.Column('published_from', sa.String(length=100), nullable=True),
    sa.Column('published_to', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('serializations', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('mal_id')
    )
    op.create_index(op.f('ix_manga_mal_id'), 'manga', ['mal_id'], unique=False)
    op.create_index(op.f('ix_manga_title'), 'manga', ['title'], unique=False)
    op.create_table('manga_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('similar_manga_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.mal_id'], ),
    sa.ForeignKeyConstraint(['similar_manga_id'], ['manga.mal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_similarity_id'), 'manga_similarity', ['id'], unique=False)
    op.create_index(op.f('ix_manga_similarity_manga_id'), 'manga_similarity', ['manga_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_similarity_manga_id'), table_name='manga_similarity')
    op.drop_index(op.f('ix_manga_similarity_id'), table_name='manga_similarity')
    op.drop_table('manga_similarity')
    op.drop_index(op.f('ix_manga_title'), table_name='manga')
    op.drop_index(op.f('ix_manga_mal_id'), table_name='manga')
    op.drop_table('manga')
    # ### end Alembic commands ###
